ReadyGOTravel/readygotravel/readygotravel/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using readygotravel.Models;

namespace readygotravel.Controllers
{
    public class QuestionnaireController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Questionnaire
        [HttpGet]
        public ActionResult Index()
        {
            List<State> result = new List<State>();
            string season = Request.QueryString["season"];
            string weather = Request.QueryString["weather"];
            string temperature = Request.QueryString["temperature"];

            System.Diagnostics.Debug.WriteLine(season);
            System.Diagnostics.Debug.WriteLine(weather);
            System.Diagnostics.Debug.WriteLine(temperature);

            if (temperature != null)
            {
                string[] tempSplit = temperature.Split('-');
                int[] tempInts = Array.ConvertAll(tempSplit, s => int.Parse(s));
                int temp1 = tempInts[0];
                int temp2 = tempInts[1];

                System.Diagnostics.Debug.WriteLine(tempInts[0]);
                System.Diagnostics.Debug.WriteLine(tempInts[1]);

                switch (season)
                {
                    case "spring":
                        if (weather != "no preference")
                        {
                            result = db.States.Where(s => s.SpringWeather == weather).Where(s => s.SpringTemp >= temp1 && s.SpringTemp <= temp2).ToList();
                        }
                        else
                        {
                            result = db.States.Where(s => s.SpringWeather == "sunny" || s.SpringWeather == "humid" || s.SpringWeather == "clear skies" || s.SpringWeather == "cloudy" || s.SpringWeather == "rainy" || s.SpringWeather == "snowy").Where(s => s.SpringTemp >= temp1 && s.SpringTemp <= temp2).ToList();
                        }
                        ViewBag.Result = "springlist";
                        break;
                    case "summer":
                        if (weather != "no preference")
                        {
                            result = db.States.Where(s => s.SummerWeather == weather).Where(s => s.SummerTemp >= temp1 && s.SummerTemp <= temp2).ToList();
                        }
                        else
                        {
                            result = db.States.Where(s => s.SummerWeather == "sunny" || s.SummerWeather == "humid" || s.SummerWeather == "clear skies" || s.SummerWeather == "cloudy" || s.SummerWeather == "rainy" || s.SummerWeather == "snowy").Where(s => s.SummerTemp >= temp1 && s.SummerTemp <= temp2).ToList();
                        }
                        ViewBag.Result = "summerlist";
                        break;
                    case "fall":
                        if (weather != "no preference")
                        {
                            result = db.States.Where(s => s.FallWeather == weather).Where(s => s.FallTemp >= temp1 && s.FallTemp <= temp2).ToList();
                        }
                        else
                        {
                            result = db.States.Where(s => s.FallWeather == "sunny" || s.FallWeather == "humid" || s.FallWeather == "clear skies" || s.FallWeather == "cloudy" || s.FallWeather == "rainy" || s.FallWeather == "snowy").Where(s => s.FallTemp >= temp1 && s.FallTemp <= temp2).ToList();
                        }
                        ViewBag.Result = "fallresult";
                        break;
                    case "winter":
                        if (weather != "no preference")
                        {
                            result = db.States.Where(s => s.WinterWeather == weather).Where(s => s.WinterTemp >= temp1 && s.WinterTemp <= temp2).ToList();
                        }
                        else
                        {
                            result = db.States.Where(s => s.WinterWeather == "sunny" || s.WinterWeather == "humid" || s.WinterWeather == "clear skies" || s.WinterWeather == "cloudy" || s.WinterWeather == "rainy" || s.WinterWeather == "snowy").Where(s => s.WinterTemp >= temp1 && s.WinterTemp <= temp2).ToList();
                        }
                        ViewBag.Result = "winterresult";
                        break;
                    case "no preference":
                        //no preference
                        if (weather != "no preference")
                        {
                            result = db.States.Where(s => s.SpringWeather == weather || s.SummerWeather == weather || s.FallWeather == weather || s.WinterWeather == weather).Where(s => s.SpringTemp >= temp1 && s.SpringTemp <= temp2 || s.SummerTemp >= temp1 && s.SummerTemp <= temp2 || s.FallTemp >= temp1 && s.FallTemp <= temp2 || s.WinterTemp >= temp1 && s.WinterTemp <= temp2).ToList();
                        }
                        else
                        {
                            result = db.States.Where(s => s.SpringWeather == "sunny" || s.SpringWeather == "humid" || s.SpringWeather == "clear skies" || s.SpringWeather == "cloudy" || s.SpringWeather == "rainy" || s.SpringWeather == "snowy" || s.SummerWeather == "sunny" || s.SummerWeather == "humid" || s.SummerWeather == "clear skies" || s.SummerWeather == "cloudy" || s.SummerWeather == "rainy" || s.SummerWeather == "snowy" || s.FallWeather == "sunny" || s.FallWeather == "humid" || s.FallWeather == "clear skies" || s.FallWeather == "cloudy" || s.FallWeather == "rainy" || s.FallWeather == "snowy" || s.WinterWeather == "sunny" || s.WinterWeather == "humid" || s.WinterWeather == "clear skies" || s.WinterWeather == "cloudy" || s.WinterWeather == "rainy" || s.WinterWeather == "snowy").Where(s => s.SpringTemp >= temp1 && s.SpringTemp <= temp2 || s.SummerTemp >= temp1 && s.SummerTemp <= temp2 || s.FallTemp >= temp1 && s.FallTemp <= temp2 || s.WinterTemp >= temp1 && s.WinterTemp <= temp2).ToList();
                        }
                        ViewBag.Result = "noprefresult";
                        break;
                    default:
                        break;
                }
                if(result.Count() == 0)
                {
                    ViewBag.Message = "I'm sorry, but there are no results for your given selections of " + season + " season, with " + weather + " weather, and " + temp1 + " to " + temp2 + " degree temperature:";
                }
                else
                {
                    ViewBag.Message = "Here are the results for your selections of " + season + " season, with " + weather + " weather, and " + temp1 + " to " + temp2 + " degree temperature:";
                }
            }
            return View(result);
        }

        public ActionResult Result()
        {
            return View();
        }
    }
}

ReadyGOTravel/readygotravel/readygotravel/Controllers/SearchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Xml;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using readygotravel.Models;
using readygotravel.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace readygotravel.Controllers
{

    public class SearchesController : Controller
    {
        
        private DBContext db = new DBContext();
        private ApplicationDbContext userDB = new ApplicationDbContext();

        // GET: Searches
        public ActionResult Index()
        {
            var searches = db.Searches.Include(s => s.Person);
            return View(searches.ToList());
        }
        
        public ActionResult Result(int? id, decimal? left)
        {
            Result result = db.Results.Find(id);

            ViewBag.Remaining = left;
            ViewBag.Total = (result.AvgFlightAmount + result.AvgHotelAmount + result.AvgFoodCost);

            //compare amount available
            if (left >= 0)
            {
                ViewBag.Result = 0;
                ViewBag.Message = "You can travel there for: ";
                ViewBag.Message2 = "And you have this much remaining: ";
            }
            else if (left >= -500)
            {
                ViewBag.Result = 1;
                ViewBag.Message = "You can almost go if you had amount this much more: ";
            }
            else
            {
                ViewBag.Result = 2;
                ViewBag.Message = "You are too broke and can't go on that budget, you would need this much more: ";
            }
                        
            //get the whole number of the average star value;
            decimal integral = Math.Truncate(result.AvgHotelStar);
            //get the decimal value of the average star value;
            decimal @decimal = result.AvgHotelStar - integral;
            //Check if the decimal value is 0, if so skip this.
            if (@decimal != 0)
            {                
                //If the decimal value is less than 0.12 set the decimal value to 0
                if(@decimal <= (decimal)0.12)
                {
                    @decimal = 0;
                }
                //If the decimal value is less than 0.37 but bigger than 0.12 set the decimal value to 0.25
                else if (@decimal <= (decimal)0.37)
                {
                    @decimal = (decimal)0.25;
                }
                //If the decimal value is less than 0.62 but bigger than 0.37 set the decimal value to 0.5
                else if (@decimal <= (decimal)0.62)
                {
                    @decimal = (decimal)0.5;
                }
                //If the decimal value is less than 0.88 but bigger than 0.62 set the decimal value to 0.75
                else if (@decimal <= (decimal)0.88)
                {
                    @decimal = (decimal)0.75;
                }
                //If the decimal value is bigger than 0.88 set the decimal value to 1
                else
                {
                    @decimal = 1;
                }
            }
            //If the decimal value = 1, add 1 to the whole number and subract 1 from the decimal value.
            if (@decimal == 1)
            {
                integral++;
                @decimal--;
            }
            //Set the whole number and decimal to the View.
            ViewBag.Stars = integral;
            ViewBag.Decimal = @decimal;

            //Present information to user
            return View(result);
        }

        // GET: Searches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Search search = db.Searches.Find(id);
            if (search == null)
            {
                return HttpNotFound();
            }
            return View(search);
        }

        // GET: Searches/Create
        public ActionResult Create()
        {
            //create the list of states
            List<string> states = new List<string>();
            states.Add("---");
            foreach(string state in db.States.Select(s => s.StateName).ToList())
            {
                states.Add(state);
            }
            ViewBag.States = states;

            //create the list of stars
            List<string> stars = new List<string>();
            stars.Add("No Preference");
            stars.Add("0-1");
            stars.Add("1-2");
            stars.Add("3-4");
            stars.Add("4-5");
            ViewBag.Stars = stars;

            //create the list of flight types
            List<string> types = new List<string>();
            types.Add("Economy");
            //types.Add("First Class");
            ViewBag.Flight = types;

            return View();
        }

        // POST: Searches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StartDate,EndDate,NumTravelers,MaxAmount")] SearchDashBoardVM searchVM, int? sAirport, int? eAirport, string HotelStarValue, string FlightType)
        {          
            //get the username of the user that is logged in.
            string userName = User.Identity.Name;

            //find the userID for the person logged in.
            string userID = userDB.Users
                .Where(u => u.UserName == userName)
                .Select(un => un.Id).FirstOrDefault();

            //find the personID for the person logged in.
            int? personID = db.People
                .Where(p => p.UserID == userID)
                .Select(u => u.PersonID).FirstOrDefault();

            int id = -5;
            
            //if there is no user logged in, set the userID to -1, otherwise set it to the user logged in.
            if (personID == null || personID == 0)
            {
                id = -1;
            }
            else
            {
                id =  (int)personID;
            }

            //Find the corresponding numbers or symbols for the given inputs of the star value and flight type.
            int star = GetHotelStarValue(HotelStarValue);
            string type = GetFlightType(FlightType);
            
            if(sAirport == null | eAirport == null)
            {
                //create the list of states
                List<string> stateList = new List<string>();
                stateList.Add("---");
                foreach (string state in db.States.Select(s => s.StateName).ToList())
                {
                    stateList.Add(state);
                }
                ViewBag.States = stateList;

                //create the list of stars
                List<string> starList = new List<string>();
                starList.Add("No Preference");
                starList.Add("0-1");
                starList.Add("1-2");
                starList.Add("3-4");
                starList.Add("4-5");
                ViewBag.Stars = starList;

                //create the list of flight types
                List<string> typeList = new List<string>();
                typeList.Add("Economy");
                //typeList.Add("First Class");
                ViewBag.Flight = typeList;

                return View();
            }

            //create the search (hopefully...)
            Search search = new Search { UserID = id, NumTravelers = searchVM.NumTravelers, StartDate = searchVM.StartDate, EndDate = searchVM.EndDate, MaxAmount = searchVM.MaxAmount, StartAirport = (int)sAirport, EndAirport = (int)eAirport, HotelStarValue = star, FlightType = type };

            if (ModelState.IsValid)
            {                               
                //Get the starting airport code from the DB
                string startAirPort = db.Airports
                    .Where(a => a.AirportID == sAirport)
                    .Select(a => a.AirportCode)
                    .FirstOrDefault();

                //Get the airport code for the ending airport
                string endAirPort = db.Airports
                    .Where(a => a.AirportID == eAirport)
                    .Select(a => a.AirportCode)
                    .FirstOrDefault();

                //Get the foodCost based on the ending state
                decimal foodCost = Math.Round(db.Airports
                    .Where(a => a.AirportID == search.EndAirport)
                    .Select(a => a.State.FoodCost)
                    .FirstOrDefault(), 2);

                //determine total days on vacation
                TimeSpan totalDays = search.EndDate - search.StartDate;

                //calcate foodCost by mulitiplying # of Days * # of Travelers * food cost average by state per day per person
                decimal totalFoodCost = Math.Round(foodCost * search.NumTravelers * Convert.ToDecimal(totalDays.TotalDays), 2);

                //Do the flight API stuff and get the average cost of flights.
                decimal flightInfo = GetFlightData(search.StartDate, search.EndDate, search.NumTravelers, startAirPort, endAirPort, type);

                //Do the hotel API stuff and get the average cost of hotels.                
                List<decimal> hotelInfo = GetHotelData(search.StartDate, search.EndDate, search.NumTravelers, endAirPort, star);
                decimal hotelCost = hotelInfo.First();
                decimal avgStar = hotelInfo.LastOrDefault();

                //calculate how much money is left over
                decimal amount = search.MaxAmount - (flightInfo + hotelCost + totalFoodCost);
                amount = Math.Round(amount, 2);

ReadyGOTravel/readygotravel/readygotravel/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="container">

    <div class="jumbotron">
        <h2>Our Team</h2><br />
        <h4>Tiffany Jansen</h4>
        <div class="row">
            <div class="col-md-3">
                <img src="@Url.Content("~/Content/Images/Tif.png")" style="width:210px; height:170px" />
                <img src="@Url.Content("~/Content/Images/readygotravel.png")" style="width:210px; height:100px" />
            </div>
            <div class="col-md-9">
                <h6>Why did you choose to be a computer scientist?</h6>
                <p id="about">
                    I originally I wanted to be a high school math teacher. I was required to take a CS class and found that it was kind of fun, but I think it was the second CS class I took that really sealed it for me. I was dreaming about making the code do what I wanted it to, and it just made me realize that the problems in Computer Science are closely related to the problems in Mathematics and I decided that CS would be a better fit for me.
                </p>
                <h6>What do you aspire to do after college?</h6>
                <p id="about">
                    I would like to do something that challenges me. I want to have to think about problems and try to fix them. I would love to have a job making algorithms or doing something mathematical, but I also really enjoy doing Software Engineering too. Honestly, I don’t know EXACTLY what I want to do, but I think it would be super fun to use my degree to do something with Computers that helps someone somewhere. I want to make a difference. I keep thinking about going to get my PhD and becoming a professor of Computer Science… I don’t know. I just have so many options that it’s hard to choose.
                </p>
                <h6>What do you like most about traveling?</h6>
                <p id="about">
                    I don’t usually travel. I have only been on 2 round-trip flights in my life, so I don’t have a lot of experience, but what I do like is the feeling of being free. When I travel, I have none of the responsibilities that I have when I’m home. I get to do what I want. I think seeing all the sights and seeing the people and comparing it to home is cool too.
                </p>
                <h6>What would your dream destination be and why?</h6>
                <p id="about">
                    My dream destination would be somewhere warm and sunny!
                </p>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <h4>Adrian Vickers</h4>
        <div class="row">
            <div class="col-md-3">
                <img src="@Url.Content("~/Content/Images/Adr.png")" style="width:210px; height:170px" />
                <img src="@Url.Content("~/Content/Images/readygotravel.png")" style="width:210px; height:100px" />
            </div>
            <div class="col-md-9">
                <h6>Why did you choose to be a computer scientist?</h6>
                <p id="about">
                    I always loved troubleshooting and building my own computers growing up.  I figured it would be great to learn more about how computers worked at a software as well as hardware level.  Then I could do something I loved and turn it into a potential profession.
                </p>
                <h6>What do you aspire to do after college?</h6>
                <p id="about">
                    Software design, or database administration sounds very appealing.  I love working with Databases and I am fascinated with storing and managing large sets of data.
                </p>
                <h6>What do you like most about traveling?</h6>
                <p id="about">
                    Knowing that there is always somewhere new to go and something new to see.  I also love the freedom of it, how you feel when you go somewhere else while stepping outside of the normal day to day grind of work/school.  You get to be somewhere/someone else for a while and simply enjoy what you worked and saved up for.
                </p>
                <h6>What would your dream destination be and why?</h6>
                <p id="about">
                    New Zealand because it has so many sites and wildlife that are so very different from most places in the world.  You get to see a variety of climate and landscapes that are very unique.  Not to mention all of the locations you could visit that have been used in multiple movies.
                </p>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <h4>Hector Acosta-Cervantes</h4>
        <div class="row">
            <div class="col-md-3">
                <img src="@Url.Content("~/Content/Images/Hec.png")" style="width:210px; height:170px" />
                <img src="@Url.Content("~/Content/Images/readygotravel.png")" style="width:210px; height:100px" />
            </div>
            <div class="col-md-9">
                <h6>Why did you choose to be a computer scientist?</h6>
                <p id="about">
                    The main reason was because I found the first computer science class I ever took to be really fun and easy. I was first introduced to computer science in my senior year in high school when I took a computer science class. I didn't have much interest in it at first, especially since it was my backup choice as an elective and I was disappointed at not getting my first choice. After some time I eventually found it to be my most enjoyable class. At the time I didn’t think about making it my future field of study but as college came around I decided to just stick with what I liked which was computer science.
                </p>
                <h6>What do you aspire to do after college?</h6>
                <p id="about">
                    I will hopefully get a decent job and make some decent money. I'm not exactly sure what kind of job I want but probably something related to software development. Gaining some experience is my main focus.
                </p>
                <h6>What do you like most about traveling?</h6>
                <p id="about">
                    I feel like I'm probably one of the worst people you can ask this question to since I don't really travel at all. The only place I have traveled to was California when I was five or six.
                </p>
                <h6>What would your dream destination be and why?</h6>
                <p id="about">
                    I don't really think about traveling anywhere but if I had to choose somewhere then probably France. I took 4 years of French in high school and it would be cool if I could actually use it for something. Maybe then I could also re-learn most of the language since I probably forgot about 75% of it.
                </p>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <h4>Stacia Fry</h4>
        <div class="row">
            <div class="col-md-3">
                <img src="@Url.Content("~/Content/Images/Sta.png")" style="width:210px; height:170px" />
                <img src="@Url.Content("~/Content/Images/readygotravel.png")" style="width:210px; height:100px" />
            </div>
            <div class="col-md-9">
                <h6>Why did you choose to be a computer scientist?</h6>
                <p id="about">
                    I decided to study computer science because I have been an avid computer user since I was 11 years old and my dad has worked and taught in this field my entire life. I kind of started on a whim after pursuing other career venues, and I’ve fallen deep in love with the problem solving aspect of coding.
                </p>
                <h6>What do you aspire to do after college?</h6>
                <p id="about">
                    Once I graduate, I hope to pursue a rewarding career in either software engineering or data science.
                </p>
                <h6>What do you like most about traveling?</h6>
                <p id="about">
                    The best part of travelling is experiencing other cultures, cuisine, and climate. I have travelled to various places both in and outside of the United States and I never want to stop. It’s such an important experience for personal growth.
                </p>
                <h6>What would your dream destination be and why?</h6>
                <p id="about">
                    My dream destination has and will always be Japan (despite having visited the country three times!). Kyoto is the most beautiful city I’ve ever seen and I cannot wait to return to its shrines and temples again and again.
                </p>
            </div>
        </div>
    </div>
</div>

ReadyGOTravel/readygotravel/readygotravel/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div class="container">
    <div class="jumbotron">
        <h2>Contact Us</h2>
        <h4>Notice any problems or errors in our site? Please inform us by filling out this form and we will look into it.</h4>
        <hr />
        @using (@Html.BeginForm("Contact", "Home", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {

            /*textbox to get name of person filling this form.*/
            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("name", "Full Name")
                    @Html.TextBox("name", null, htmlAttributes: new { @class = "form-control", type = "text", required = "required" })
                </div>
            </div>

            /*textbox to get email of person filling this form.*/
            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("email", "Email")
                    @Html.TextBox("email", null, htmlAttributes: new { @class = "form-control", type = "email", required = "required" })
                </div>
            </div>

            /*checkbox to know if person filling this form has an account.*/
            <div class="form-group">
                <div class="col-md-3">
                    @Html.Label("ownAccount", "Do you have an account?")
                    @Html.CheckBox("ownAccount", false)
                </div>
            </div>

            /*dropdown to know what type of problem the person filling this form has.*/
            <div class="form-group">
                <div class="col-md-2">
                    <label for="catagory">Problem Catagory</label>
                    <select class="form-control" id="catagory" name="catagory">
                        <option value="Unspecified">Unspecified</option>
                        <option value="Home Page">Home Page</option>
                        <option value="Account">Account</option>
                        <option value="Search Results">Search Results</option>
                        <option value="Flight Information">Flight Information</option>
                        <option value="Hotel Information">Hotel Information</option>
                    </select>
                </div>
            </div>

            /*textbox to get description of problem by person filling out this form.*/
            <div class="form-group">
                <div class="col-md-5">
                    @Html.Label("description", "Description of Problem")
                    @Html.TextArea("description", null, new { @class = "form-control", @id = "longText1", rows = "10", required = "required" })
                </div>
            </div>

            <br />
            @Html.TextBox("submited", "Submit", htmlAttributes: new { @class = "btn btn-primary", type = "submit" })
            <br />

        }
    </div>
</div>

ReadyGOTravel/readygotravel/readygotravel/Views/Home/Index.cshtml
@{
    ViewBag.Title = "ReadyGO Travel - Home";
}

<div class="info-container">
    <div class="container-fluid">
        <div class="image-bar">
            <div class="buttons">
                <div class="row justify-content-center">
                    <div class="col-md-4">
                        <button type="button" class="btn btn-light" onclick="location.href='@Url.Action("Index", "Questionnaire")'">
                            Don't know where to go? <br />
                            We're here to help!
                        </button>
                    </div><div class="col--md-4"></div>
                    <div class="col--md-4">
                        <button type="button" class="btn btn-light" onclick="location.href='@Url.Action("Create", "Searches")'">Have your budget <br /> and destination?</button>
                    </div>
                </div>
            </div>
            <div class="content">
                <p><h2>Welcome to ReadyGO Travel!</h2></p>
                <br />
                <p>Welcome to ReadyGO Travel. We are here to help you plan your travel budget for your trip! If you have your budget and location already decided, click the button on the right above to find the average prices of flights and hotels. If you have your budget but not quite sure yet on where you want to go, click the button the left above and we'll help you narrow down a location for your getaway vacation!</p>
            </div>
            <hr />
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4" id="megaTable">
                    <div class="mx-auto d-block">
                        <h6>@Html.ActionLink("Mission Statement", "Mission")</h6>
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
            </div>
        </div>
</div>

ReadyGOTravel/readygotravel/readygotravel/Views/Home/Mission.cshtml
@{
    ViewBag.Title = "Mission";
}
<div class="container">
    <div class="jumbotron">
        <div class="mx-auto d-block" align="center">
            <h2><u>Mission Statement</u></h2>
        </div>
        <div class="row">
            <div class="col-md-3">
                <img src="@Url.Content("~/Content/Images/logo.png")" style="width:210px; height:170px" />
            </div>
            <div class="col-md-6" style="text-align:center">
                <h4>
                    As the founders of <i>ReadyGO-Travel</i>, our goal is to provide fast and efficient travel budget information.
                    Our intention is to guide those who are wanting to travel affordably, expenditure guidance so that they can plan ahead and pursue their dream destination.
                </h4>
            </div>
            <div class="col-md-3">
                <img src="@Url.Content("~/Content/Images/logo.png")" style="width:210px; height:170px" />
            </div>
        </div>
        </div>
    </div>